# NUMPY

In [1]:
import numpy as np

In [2]:
np.__version__ # this code is to check numpy version (double undersocre)

'1.26.4'

In [3]:
import sys
sys.version

'3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 15:03:56) [MSC v.1929 64 bit (AMD64)]'

# Creating Arrays

In [4]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [5]:
type(my_list)

list

In [6]:
arr = np.array(my_list) # this code is to convert list to array
                        # create new variable and following code


In [7]:
type(arr)

numpy.ndarray

# arange  function
# start, stop, step

In [8]:
np.arange(15)  #  15 INTEGER DATA TYPE

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

- #### The above output show from 0 to 14, the arrange functon  will arange the values till the mentioned number

In [9]:
np.arange(3.0) # 3.0 IS FLOAT DATA TYPE

array([0., 1., 2.])

In [10]:
np.arange(10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,5) # two arguments

array([0, 1, 2, 3, 4])

In [12]:
np.arange(10,20) 

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

- #### in two arguments arange function starts from the first argument and end second argument value(n-1)

In [13]:
np.arange(20,10)

array([], dtype=int32)

- #### The above output showing as error(empty error) because, the first argument is greater that second  argument.

- #### The numpy cannot allow arnage function because first argument value is greater than second argument.

In [14]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [15]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [16]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [17]:
ar = np.arange(-30,20) # to optimise the code we crearte variable
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [18]:
np.arange(10,10)

array([], dtype=int32)

- #### The above output showing as error(empty error) because, the first argument is equal to second  argument.

- #### The arange function allows atleat one argument or two arguments or three argument

- #### the arange argument cannot be more than 3 arguments


In [19]:
np.arange(10,30,5) # 10 is first argument
                   # 30 is second argument
                   # 5 is step 

array([10, 15, 20, 25])

In [20]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [21]:
np.arange(0,10,3,5)

TypeError: Cannot interpret '5' as a data type

-  #### The above output is showing as error because the arange function cannot allow 4 argunment only 3 arguments

# Zeros function
# shape, dtype = float, order, link

In [22]:
np.zeros(3) # parameter tunning

array([0., 0., 0.])

- #### The above output shows all zeros in float, because system by default shows zeros in float data type

- #### This process is called as parameter tunning.

- ####  To convert float zeros into integer zero, see below

In [23]:
np.zeros(5, dtype = int) # conversion of float zeros to integer zeros
                         # hyperparameter tunning
                         # one dimension  array

array([0, 0, 0, 0, 0])

- #### The process of changing the float zeros to integer zeros is know as hyperparemeter tunning

- #### in large language model we call it as finetune

In [24]:
np.zeros((2,2), dtype = int) # two rows and two coloums
                             # two dimensions array
                        

array([[0, 0],
       [0, 0]])

In [25]:
zero = np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [26]:
zero = np.zeros([2,2])
print(zero)

print('####')
print(type(zero))

[[0. 0.]
 [0. 0.]]
####
<class 'numpy.ndarray'>


In [27]:
zero = np.zeros([2,2], dtype = int) # integer zeros
print(zero)

print('####')
print(type(zero))

[[0 0]
 [0 0]]
####
<class 'numpy.ndarray'>


In [28]:
np.zeros((2,10)) # 2 means row (left)
                 # 10 means columns (right)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [29]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [30]:
n = (6,7)
n1 = (6,8)
print(np.zeros(n))

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [31]:
print(np.zeros(n, dtype = int))

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [32]:
print(type(n))

<class 'tuple'>


# ones function  
# shape, dtype = float, order, link

In [33]:
np.ones(3)

array([1., 1., 1.])

In [34]:
np.ones(4, dtype=int) # conversion to integer

array([1, 1, 1, 1])

In [35]:
np.ones(4)

array([1., 1., 1., 1.])

In [36]:
np.ones((5,4)) # float

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [37]:
np.ones((5,4), dtype = int) # integer

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [38]:
np.twos(5,6)

AttributeError: module 'numpy' has no attribute 'twos'

# twos function doesnt work in numpy, numpy allows only in-built function

# range function

In [39]:
range(5)

range(0, 5)

In [40]:
r = range(5)
r

range(0, 5)

In [41]:
list(range(5)) # to display the number list

[0, 1, 2, 3, 4]

In [42]:
tuple(range(5)) # to display the number tuple

(0, 1, 2, 3, 4)

In [43]:
for i in r:
    print(i)

0
1
2
3
4


In [44]:
range(1,10)

range(1, 10)

In [45]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [46]:
list(range(1,10,3)) # 1 means 1st argument
                    # 10 means 2nd argument
                    # 3 means step 

[1, 4, 7]

# rand function (Random function)

In [47]:
rand(3,2)

NameError: name 'rand' is not defined

In [48]:
rand(3,2)
random.rand(3,2)

NameError: name 'rand' is not defined

- #### The above two output showing as error because rand is fucntion, to process the functon we required module, to porcess the module we require libraby (numpy)

`Rand fucntion`

In [49]:
np.random.rand(3,2) # Three rows andt two columns

array([[0.23449226, 0.90275683],
       [0.29431064, 0.16738819],
       [0.77741888, 0.56446939]])

- #### The above output keeps changing as you execute the code

In [50]:
np.random.rand(5)

array([0.38405485, 0.83040018, 0.89769623, 0.57573996, 0.45229566])

In [51]:
np.random.rand(2,4)

array([[0.65161155, 0.89398736, 0.31237023, 0.3257627 ],
       [0.16915494, 0.58927851, 0.48472193, 0.13763654]])

`Randint function`

In [52]:
np.random.randint(4)

0

- #### The above output showing as 3 because the randint function allows to diplay value which is btween 0 to 4 but not 4 (mentiond value) it excludes maximun value.

In [53]:
np.random.randint(2,4)

3

- #### The output changes it values as you execute code but only between 2 to 4 as metioned in the code

In [54]:
np.random.randint(10,20,3)  # 3 means the output display 3 numbers 

array([15, 19, 12])

In [55]:
np.random.randint(10,20,4) 

array([12, 10, 12, 12])

In [56]:
np.random.randint(10,40,(10,10)) # 10 row and 10 columns

array([[33, 38, 18, 11, 16, 11, 14, 14, 11, 22],
       [32, 22, 16, 12, 30, 34, 27, 33, 34, 22],
       [27, 14, 11, 23, 27, 29, 19, 32, 38, 16],
       [35, 27, 39, 37, 29, 38, 15, 25, 14, 24],
       [23, 33, 28, 37, 24, 14, 30, 37, 24, 38],
       [10, 31, 20, 26, 15, 19, 13, 13, 27, 11],
       [38, 27, 31, 14, 24, 26, 29, 19, 32, 29],
       [28, 38, 22, 29, 32, 11, 38, 14, 34, 11],
       [30, 16, 29, 14, 31, 33, 37, 33, 24, 21],
       [31, 33, 32, 18, 28, 26, 26, 13, 36, 13]])

In [57]:
b = np.random.randint(10,40,(5,6))
b # 5 rows and 6 columns

array([[32, 22, 26, 29, 31, 12],
       [31, 38, 11, 29, 29, 14],
       [32, 10, 32, 13, 26, 39],
       [17, 25, 28, 14, 22, 26],
       [36, 10, 17, 37, 23, 36]])

In [58]:
print(type(b))

<class 'numpy.ndarray'>


# Slicing index in numpy

In [59]:
b[:]

array([[32, 22, 26, 29, 31, 12],
       [31, 38, 11, 29, 29, 14],
       [32, 10, 32, 13, 26, 39],
       [17, 25, 28, 14, 22, 26],
       [36, 10, 17, 37, 23, 36]])

In [60]:
for i in enumerate(b):
    print(i)

(0, array([32, 22, 26, 29, 31, 12]))
(1, array([31, 38, 11, 29, 29, 14]))
(2, array([32, 10, 32, 13, 26, 39]))
(3, array([17, 25, 28, 14, 22, 26]))
(4, array([36, 10, 17, 37, 23, 36]))


In [61]:
b[1:3]

array([[31, 38, 11, 29, 29, 14],
       [32, 10, 32, 13, 26, 39]])

In [62]:
b[1,2] # 1 means index see above output
       # 2 means (2nd index value in 1 index)

11

In [63]:
b[1,3]

29

In [64]:
b[2:3]

array([[32, 10, 32, 13, 26, 39]])

In [65]:
b[0:-2] # -2 means removes last 2 rows

array([[32, 22, 26, 29, 31, 12],
       [31, 38, 11, 29, 29, 14],
       [32, 10, 32, 13, 26, 39]])

In [66]:
b[0:-3] #-3 means removes last 3 rows

array([[32, 22, 26, 29, 31, 12],
       [31, 38, 11, 29, 29, 14]])

In [67]:
b[0:-4] #-4 means removes last 4 rows

array([[32, 22, 26, 29, 31, 12]])

In [68]:
b[-5:-3]

array([[32, 22, 26, 29, 31, 12],
       [31, 38, 11, 29, 29, 14]])

# OPERATIONS

In [69]:
a = np.random.randint(10,20,10)
a# 5 rows and 6 columns

array([15, 17, 10, 12, 18, 10, 11, 18, 16, 17])

In [70]:
id(a) # memory location address of variable a

2436879942160

In [71]:
arr2 = np.random.randint(0,100,(10,10)) 
arr2
# 10 into 10 matrix with random numbers from 0 to 99

array([[53, 43, 73, 18, 88, 40, 99, 74, 71, 87],
       [42,  6,  5, 67, 86, 55, 93, 68, 90, 33],
       [13, 56, 20, 59, 82, 20,  8, 71, 97, 11],
       [59, 49, 84, 77, 73, 67, 17, 73, 22, 82],
       [39, 58, 97, 74,  9, 29, 78, 78, 26, 88],
       [56, 87, 38, 54,  2, 56, 13, 82, 22, 65],
       [43, 26, 37, 21, 53, 82, 38, 50, 94, 97],
       [30, 92, 28, 99,  3, 69, 47, 64, 33, 55],
       [79, 49, 90, 16, 75, 31, 74, 91,  5, 16],
       [94, 71, 91, 43,  8, 11, 16, 16, 23, 37]])

In [72]:
arr2[:]

array([[53, 43, 73, 18, 88, 40, 99, 74, 71, 87],
       [42,  6,  5, 67, 86, 55, 93, 68, 90, 33],
       [13, 56, 20, 59, 82, 20,  8, 71, 97, 11],
       [59, 49, 84, 77, 73, 67, 17, 73, 22, 82],
       [39, 58, 97, 74,  9, 29, 78, 78, 26, 88],
       [56, 87, 38, 54,  2, 56, 13, 82, 22, 65],
       [43, 26, 37, 21, 53, 82, 38, 50, 94, 97],
       [30, 92, 28, 99,  3, 69, 47, 64, 33, 55],
       [79, 49, 90, 16, 75, 31, 74, 91,  5, 16],
       [94, 71, 91, 43,  8, 11, 16, 16, 23, 37]])

In [73]:
arr2[-5:-3]

array([[56, 87, 38, 54,  2, 56, 13, 82, 22, 65],
       [43, 26, 37, 21, 53, 82, 38, 50, 94, 97]])

In [74]:
arr2[-8:-4]

array([[13, 56, 20, 59, 82, 20,  8, 71, 97, 11],
       [59, 49, 84, 77, 73, 67, 17, 73, 22, 82],
       [39, 58, 97, 74,  9, 29, 78, 78, 26, 88],
       [56, 87, 38, 54,  2, 56, 13, 82, 22, 65]])

In [75]:
arr2[-9:4]

array([[42,  6,  5, 67, 86, 55, 93, 68, 90, 33],
       [13, 56, 20, 59, 82, 20,  8, 71, 97, 11],
       [59, 49, 84, 77, 73, 67, 17, 73, 22, 82]])

In [76]:
arr2[::]

array([[53, 43, 73, 18, 88, 40, 99, 74, 71, 87],
       [42,  6,  5, 67, 86, 55, 93, 68, 90, 33],
       [13, 56, 20, 59, 82, 20,  8, 71, 97, 11],
       [59, 49, 84, 77, 73, 67, 17, 73, 22, 82],
       [39, 58, 97, 74,  9, 29, 78, 78, 26, 88],
       [56, 87, 38, 54,  2, 56, 13, 82, 22, 65],
       [43, 26, 37, 21, 53, 82, 38, 50, 94, 97],
       [30, 92, 28, 99,  3, 69, 47, 64, 33, 55],
       [79, 49, 90, 16, 75, 31, 74, 91,  5, 16],
       [94, 71, 91, 43,  8, 11, 16, 16, 23, 37]])

In [77]:
arr2[::-1] # reverse slicing

array([[94, 71, 91, 43,  8, 11, 16, 16, 23, 37],
       [79, 49, 90, 16, 75, 31, 74, 91,  5, 16],
       [30, 92, 28, 99,  3, 69, 47, 64, 33, 55],
       [43, 26, 37, 21, 53, 82, 38, 50, 94, 97],
       [56, 87, 38, 54,  2, 56, 13, 82, 22, 65],
       [39, 58, 97, 74,  9, 29, 78, 78, 26, 88],
       [59, 49, 84, 77, 73, 67, 17, 73, 22, 82],
       [13, 56, 20, 59, 82, 20,  8, 71, 97, 11],
       [42,  6,  5, 67, 86, 55, 93, 68, 90, 33],
       [53, 43, 73, 18, 88, 40, 99, 74, 71, 87]])

In [78]:
arr2[::-3] 

array([[94, 71, 91, 43,  8, 11, 16, 16, 23, 37],
       [43, 26, 37, 21, 53, 82, 38, 50, 94, 97],
       [59, 49, 84, 77, 73, 67, 17, 73, 22, 82],
       [53, 43, 73, 18, 88, 40, 99, 74, 71, 87]])

In [79]:
arr

array([0, 1, 2, 3, 4, 5])

In [80]:
arr.max() # MAXIMUM VALUE

5

In [81]:
arr.min() # MINIMMUM VALUE

0

In [82]:
arr.mean()  # MEAN VALUE  (average value)

2.5

In [83]:
arr.median() # MEDIAN VALUE

AttributeError: 'numpy.ndarray' object has no attribute 'median'

- ####  The above output is showing error because median is not exit in  the in-built funtion in numpy

- ####  To execute median we need to import `Median`, see below

In [84]:
from numpy import * 
a = array([1,2,3,4,9])
median(a)
# star means it will import all the 217 function in numpy to fit the code.


3.0

In [85]:
arr

array([0, 1, 2, 3, 4, 5])

In [86]:
arr.reshape(3,2) #  reshaping 3 in to 2 matrix

array([[0, 1],
       [2, 3],
       [4, 5]])

In [87]:
arr.reshape(6,1) # 6 rows and 1 columns matrix

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [88]:
arr.reshape(4,2) 

ValueError: cannot reshape array of size 6 into shape (4,2)

- #### The reshape only will happen when it fits to its rows and columns

- #### The above output showing as error because, the total elements from 0 to 5 is 6, but in the above reshape code we have mention 4 into 2 matrix whic is 8   that is not possible


In [89]:
# reshape orders (C,F,A)

In [90]:
arr

array([0, 1, 2, 3, 4, 5])

In [91]:
arr.reshape(2,3,order ='C')  # 

array([[0, 1, 2],
       [3, 4, 5]])

In [92]:
arr.reshape(2,3,order ='F') # F means it will shuffle rows to columns and columns to rows

array([[0, 2, 4],
       [1, 3, 5]])

In [93]:
arr.reshape(2,3,order ='A') 

array([[0, 1, 2],
       [3, 4, 5]])

# INDEXING

In [94]:
mat = np.arange(0,100).reshape(10,10) 
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [95]:
row = 4
col = 5

In [96]:
col 

5

In [97]:
row

4

In [98]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [99]:
mat[row,col] # check 4th row and 5th colun

45

In [100]:
mat[4,5]

45

In [101]:
mat[6,8] # give any row and column index

68

In [102]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [103]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [104]:
mat[0:10:4]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [105]:
mat[:4]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [106]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [107]:
mat[::-2] # two semi-colums means reverse ans -2 means step

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [108]:
mat[::-4]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

# SLICING IN MATRIX

In [109]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [110]:
for i in enumerate (mat):
    print(i)

(0, array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))
(1, array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]))
(2, array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29]))
(3, array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39]))
(4, array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49]))
(5, array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59]))
(6, array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69]))
(7, array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79]))
(8, array([80, 81, 82, 83, 84, 85, 86, 87, 88, 89]))
(9, array([90, 91, 92, 93, 94, 95, 96, 97, 98, 99]))


In [111]:
mat[2:6,2:4]

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

#### The above output showing result as follows
   - 2:6 means row form 2nd index to 5th index 
   - 2:4 means columns from 2nd index to 4th columns

##### Note: n-1 is applicable 

In [112]:
mat[5:7,3:8]

array([[53, 54, 55, 56, 57],
       [63, 64, 65, 66, 67]])

In [113]:
mat[0,1] # 0th index row  and 1st element of the same row

1

In [114]:
mat[5,6] # 5th index row and 6th element of the same row

56

In [115]:
mat[2:3,2:3]

array([[22]])

# MASKING (filter)

In [116]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [117]:
id(mat)

2436879951472

In [118]:
mat < 50 # to check either  elements below fifty  are less than fifty

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [119]:
mat > 50 # to check either  elements after fifty  are greater than fifty

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [120]:
mat[mat<50] # to check, what are the elements are below fifty 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [121]:
mat[mat>50] # to check, what are the elements are after fifty 

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [122]:
mat[mat==50] # to check how many smane elemtens are present 

array([50])

In [123]:
mat[mat!=50] # to check the elemtns which are not 50

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [124]:
mat[mat>=50]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

- ### In python index begins from 0 (left index 0 and righnt index -1)

- ### Matrix (2,3) -- 2nd row and 3rd element of same row, it gives only one value

- ### n-1 formula is always applicable

# END